// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"time"
)

const TableNameProjectAPI = "project_apis"

// ProjectAPI mapped from table <project_apis>
type ProjectAPI struct {
	ID             int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID      int       `gorm:"column:project_id;not null;comment:所属项目id" json:"project_id"`
	DirectoryID    int       `gorm:"column:directory_id;not null;comment:所属目录id" json:"directory_id"`
	Name           string    `gorm:"column:name;not null;comment:接口名称" json:"name"`
	Path           string    `gorm:"column:path;not null;comment:接口地址" json:"path"`
	Method         string    `gorm:"column:method;not null;comment:请求类型 GET POST ...." json:"method"`
	RequestHeaders string    `gorm:"column:request_headers;comment:请求头" json:"request_headers"`
	RequestQuery   string    `gorm:"column:request_query;comment:query参数" json:"request_query"`
	RequestPath    string    `gorm:"column:request_path;comment:path参数" json:"request_path"`
	RequestBody    string    `gorm:"column:request_body;comment:请求体" json:"request_body"`
	ResponseBody   string    `gorm:"column:response_body;comment:响应参数" json:"response_body"`
	Desc           string    `gorm:"column:desc;comment:接口说明" json:"desc"`
	Seq            int       `gorm:"column:seq;not null;default:10;comment:排序号从小到大排序" json:"seq"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ProjectAPI's table name
func (*ProjectAPI) TableName() string {
	return TableNameProjectAPI
}
