// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

const TableNameProjectUser = "project_users"

// ProjectUser mapped from table <project_users>
type ProjectUser struct {
	ProjectID int `gorm:"column:project_id;primaryKey" json:"project_id"`
	UserID    int `gorm:"column:user_id;primaryKey" json:"user_id"`
}

// TableName ProjectUser's table name
func (*ProjectUser) TableName() string {
	return TableNameProjectUser
}
