// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dto

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Account   string    `gorm:"column:account;not null;comment:账号" json:"account"`
	Passwd    string    `gorm:"column:passwd;not null;comment:密码" json:"passwd"`
	NickName  string    `gorm:"column:nick_name;not null;comment:昵称" json:"nick_name"`
	Status    int       `gorm:"column:status;not null;comment:状态：1：正常  0：禁用" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
